Repository Modalities/modalities, pull requests merged in 2024-08, with the labels that each got.

#213 Fix number conversion
  src/modalities/utils/number_conversion.py
  tests/dataloader/test_dataloader.py
  tests/dataloader/yaml_configs/dataloader_with_fixed_num_batches.yaml
  tests/dataloader/yaml_configs/skipped_dataloader.yaml
  tests/end2end_tests/gpt2_train_num_steps_8.yaml
  tests/end2end_tests/gpt2_warm_start_from_step_4.yaml
  tests/utils/test_number_conversion.py
Labels: bug

#211 Fix Getting Started Example
  .github/pull_request_template.md
  examples/getting_started/example_config.yaml
  examples/getting_started/run_getting_started_example.sh
  tests/run_distributed_tests.sh
  tests/tests.py
Labels: documentation, enhancement

#215 Compute MFU
  src/modalities/models/gpt2/gpt2_model.py
  src/modalities/trainer.py
  src/modalities/utils/mfu.py
  tests/run_distributed_tests.sh
  tests/test_yaml_configs/gpt2_config_mfu.yaml
  tests/utils/test_mfu.py
Labels: enhancement

#234 Docs: Add Docstrings to Files Related to Data Processing
  src/modalities/dataloader/create_index.py
  src/modalities/dataloader/create_packed_data.py
  src/modalities/dataloader/dataloader.py
  src/modalities/dataloader/dataloader_factory.py
  src/modalities/dataloader/dataset.py
  src/modalities/dataloader/dataset_factory.py
  src/modalities/dataloader/large_file_lines_reader.py
  src/modalities/dataloader/samplers.py
Labels: documentation

#240 Docstrings missing
  src/modalities/__main__.py
  src/modalities/checkpointing/checkpoint_conversion.py
  src/modalities/config/component_factory.py
  src/modalities/config/config.py
  src/modalities/evaluator.py
  src/modalities/gym.py
  src/modalities/registry/components.py
  src/modalities/registry/registry.py
  src/modalities/running_env/cuda_env.py
  src/modalities/tokenization/tokenizer_wrapper.py
  src/modalities/utils/number_conversion.py
Labels: documentation

#233 Add Docstrings
  src/modalities/__main__.py
  src/modalities/checkpointing/checkpoint_conversion.py
  src/modalities/checkpointing/checkpoint_loading.py
  src/modalities/checkpointing/checkpoint_saving.py
  src/modalities/checkpointing/checkpoint_saving_execution.py
  src/modalities/checkpointing/checkpoint_saving_instruction.py
  src/modalities/checkpointing/checkpoint_saving_strategies.py
  src/modalities/checkpointing/fsdp/fsdp_checkpoint_loading.py
  src/modalities/checkpointing/fsdp/fsdp_checkpoint_saving.py
  src/modalities/checkpointing/torch/torch_checkpoint_loading.py
  src/modalities/checkpointing/torch/torch_checkpoint_saving.py
  src/modalities/config/component_factory.py
  src/modalities/config/config.py
  src/modalities/dataloader/create_index.py
  src/modalities/dataloader/create_packed_data.py
  src/modalities/dataloader/dataloader.py
  src/modalities/dataloader/dataloader_factory.py
  src/modalities/dataloader/dataset.py
  src/modalities/dataloader/dataset_factory.py
  src/modalities/dataloader/large_file_lines_reader.py
  src/modalities/dataloader/samplers.py
  src/modalities/evaluator.py
  src/modalities/gym.py
  src/modalities/models/coca/attention_pooling.py
  src/modalities/models/coca/coca_model.py
  src/modalities/models/coca/collator.py
  src/modalities/models/coca/multi_modal_decoder.py
  src/modalities/models/coca/text_decoder.py
  src/modalities/models/components/layer_norms.py
  src/modalities/models/gpt2/collator.py
  src/modalities/models/gpt2/gpt2_model.py
  src/modalities/models/gpt2/pretrained_gpt_model.py
  src/modalities/models/huggingface/huggingface_model.py
  src/modalities/models/huggingface_adapters/hf_adapter.py
  src/modalities/models/model.py
  src/modalities/models/model_factory.py
  src/modalities/models/utils.py
  src/modalities/models/vision_transformer/vision_transformer_model.py
  src/modalities/registry/components.py
  src/modalities/registry/registry.py
  src/modalities/running_env/cuda_env.py
  src/modalities/tokenization/tokenizer_wrapper.py
  src/modalities/trainer.py
  src/modalities/training/gradient_clipping/fsdp_gradient_clipper.py
  src/modalities/training/gradient_clipping/fsdp_gradient_clipper_config.py
  src/modalities/training/gradient_clipping/gradient_clipper.py
  src/modalities/utils/number_conversion.py
  tests/run_distributed_tests.sh
Labels: documentation
