Repository Modalities/modalities, pull requests merged in 2024-04, with the labels that each got.

#62 Draft: Feature overview
  docs/supported_features.md
Labels: documentation

#100 Grad norm logging
  config_files/training/config_example_coca.yaml
  src/modalities/config/config.py
  src/modalities/evaluator.py
  src/modalities/gym.py
  src/modalities/loss_functions.py
  src/modalities/trainer.py
  src/modalities/utils/gradient_clipping.py
  tests/conftest.py
  tests/utils/test_gradient_clipping.py
Labels: enhancement

#107 Improving throughput for PackedDataGenerator
  config_files/data_preparation/packed_cc_en_2048.yaml
  src/modalities/__main__.py
  src/modalities/config/config.py
  src/modalities/dataloader/create_packed_data.py
Labels: enhancement

#115 fix: fixed tensor reshape operations
  config_files/training/config_lorem_ipsum.yaml
  src/modalities/models/gpt2/gpt2_model.py
Labels: bug

#112 Fix getting started example
  examples/getting_started/README.md
  examples/getting_started/example_config.yaml
  examples/getting_started/example_dataset_config_test.yaml
  examples/getting_started/example_dataset_config_train.yaml
  examples/getting_started/example_text_generation_config.yaml
  examples/getting_started/tokenizer/tokenizer_config.json
Labels: documentation, enhancement

#118 refactor: fixed loss logging during gradient accumulation and gradient clipping
  src/modalities/trainer.py
Labels: bug, enhancement
